name: Build
on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup override set stable
          rustup update stable
          rustup component add rustfmt clippy

      - uses: Swatinem/rust-cache@v2
      - name: Check and Test
        run: cargo fmt -- --check && cargo clippy --release -- -Dwarnings && cargo test --release

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: spacedisplay-amd64_linux
          path: ${{github.workspace}}/target/release/spacedisplay

  build-linux-snap:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Rename built snap
        run: mv ${{ steps.snapcraft.outputs.snap }} spacedisplay-amd64.snap

      - name: Upload snap
        uses: actions/upload-artifact@v3
        with:
          name: spacedisplay-amd64-snap
          path: ${{github.workspace}}/spacedisplay-amd64.snap

  build-macos:
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup override set stable
          rustup update stable
          rustup component add rustfmt clippy

      - uses: Swatinem/rust-cache@v2
      - name: Check and Test
        run: cargo fmt -- --check && cargo clippy --release -- -Dwarnings && cargo test --release

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: spacedisplay-macos
          path: ${{github.workspace}}/target/release/spacedisplay

  build-win:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup override set stable
          rustup update stable
          rustup component add rustfmt clippy

      - uses: Swatinem/rust-cache@v2
      - name: Check and Test
        run: cargo fmt -- --check && cargo clippy --release -- -Dwarnings && cargo test --release

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: spacedisplay-win64
          path: ${{github.workspace}}/target/release/spacedisplay.exe

  add-release-assets:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [ build-win, build-linux, build-linux-snap, build-macos ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Display structure of downloaded files
        working-directory: artifacts
        run: ls -R

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/spacedisplay-win64/spacedisplay.exe
          tag: ${{ github.ref }}
          asset_name: spacedisplay-win64.exe
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/spacedisplay-amd64_linux/spacedisplay
          tag: ${{ github.ref }}
          asset_name: spacedisplay-amd64_linux
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/spacedisplay-amd64-snap/spacedisplay-amd64.snap
          tag: ${{ github.ref }}
          asset_name: spacedisplay-amd64_linux.snap
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/spacedisplay-macos/spacedisplay
          tag: ${{ github.ref }}
          asset_name: spacedisplay-macos
          overwrite: true
